Repository headlamp-k8s/plugins, pull requests merged in 2025-06, with the labels that each got.

#267 Add security policy with SECURITY.md
  SECURITY.md
Labels: security

#286 minikube: Fix stop to leave context in .kube/config
  minikube/src/CommandCluster/CommandCluster.tsx
Labels: bug, minikube

#263 github/workflows/build-and-publish-image: Set top level permissions
  .github/workflows/build-and-publish-image.yml
Labels: security

#296 Bump pbkdf2 to 3.1.3
  app-catalog/package-lock.json
  backstage/package-lock.json
  cert-manager/package-lock.json
  flux/package-lock.json
  karpenter/package-lock.json
  keda/package-lock.json
  kompose/package-lock.json
  minikube/package-lock.json
  opencost/package-lock.json
  plugin-catalog/package-lock.json
  prometheus/package-lock.json
Labels: dependencies

#287 KEDA: Update dependencies
  keda/package-lock.json
Labels: dependencies
